# Generated by Django 6.1.1 on 2026-09-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turi', models.CharField(choices=[('ichimlik', 'Ichimlik'), ('ovqat', 'Ovqat'), ('dessert', 'Dessert'), ('snack', 'Snack')], max_length=20)),
                ('status', models.CharField(choices=[('mavjud', 'Mavjud'), ('yoq', "Yo'q")], default='mavjud', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
