# Generated by Django 6.1.1 on 2026-09-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_summa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manzil', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('long', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('YARATILDI', 'Yaratildi'), ('TAYYORLANMOQDA', 'Tayyorlanmoqda'), ('YETKAZILMOQDA', 'Yetkazilmoqda'), ('YETKAZILDI', 'Yetkazildi')], default='YARATILDI', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
